# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SBAGallery' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SBAGallery
    pod 'Hero', '~> 1.4.0'

  target 'SBAGalleryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SBAGalleryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
